export const api =
  "https://api.themoviedb.org/3/movie/343611?api_key=75d070b0d9fe8f50fe835510415187cb";

export const reacher = {
  adult: false,
  backdrop_path: "/ww1eIoywghjoMzRLRIcbJLuKnJH.jpg",
  belongs_to_collection: {
    id: 403374,
    name: "Jack Reacher Collection",
    poster_path: "/qtafXiYDUMKxzsssU41qWey5oiT.jpg",
    backdrop_path: "/vViRXFnSyGJ2fzMbcc5sqTKswcd.jpg",
  },
  budget: 60000000,
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 53,
      name: "Thriller",
    },
  ],
  homepage: "",
  id: 343611,
  imdb_id: "tt3393786",
  original_language: "en",
  original_title: "Jack Reacher: Never Go Back",
  overview:
    "When Major Susan Turner is arrested for treason, ex-investigator Jack Reacher undertakes the challenging task to prove her innocence and ends up exposing a shocking conspiracy.",
  popularity: 54.174,
  poster_path: "/cOg3UT2NYWHZxp41vpxAnVCOC4M.jpg",
  production_companies: [
    {
      id: 82819,
      logo_path: "/gXfFl9pRPaoaq14jybEn1pHeldr.png",
      name: "Skydance Media",
      origin_country: "US",
    },
    {
      id: 83645,
      logo_path: null,
      name: "Huahua Media",
      origin_country: "CN",
    },
    {
      id: 3407,
      logo_path: "/iVMjKOFyRvm9PW45lW1wW6TSvnj.png",
      name: "Shanghai Film Group",
      origin_country: "CN",
    },
    {
      id: 21777,
      logo_path: null,
      name: "TC Productions",
      origin_country: "US",
    },
    {
      id: 4,
      logo_path: "/gz66EfNoYPqHTYI4q9UEN4CbHRc.png",
      name: "Paramount",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "CN",
      name: "China",
    },
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2016-10-19",
  revenue: 162100000,
  runtime: 118,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Justice is Coming.",
  title: "Jack Reacher: Never Go Back",
  video: false,
  vote_average: 5.968,
  vote_count: 4611,
};

export const img_url = "https://image.tmdb.org/t/p/original/";

export const LIST_POPULAR = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg",
      genre_ids: [28, 12, 14],
      id: 572802,
      original_language: "en",
      original_title: "Aquaman and the Lost Kingdom",
      overview:
        "Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.",
      popularity: 5876.8,
      poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
      release_date: "2023-12-20",
      title: "Aquaman and the Lost Kingdom",
      video: false,
      vote_average: 6.908,
      vote_count: 980,
    },
    {
      adult: false,
      backdrop_path: "/r1eCvALF6fN7anVYL8Zn7PaceD1.jpg",
      genre_ids: [35, 10751, 14],
      id: 787699,
      original_language: "en",
      original_title: "Wonka",
      overview:
        "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
      popularity: 3324.613,
      poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
      release_date: "2023-12-06",
      title: "Wonka",
      video: false,
      vote_average: 7.208,
      vote_count: 1538,
    },
    {
      adult: false,
      backdrop_path: "/meyhnvssZOPPjud4F1CjOb4snET.jpg",
      genre_ids: [16, 12, 35, 10751, 28],
      id: 940551,
      original_language: "en",
      original_title: "Migration",
      overview:
        "After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
      popularity: 2295.419,
      poster_path: "/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
      release_date: "2023-12-06",
      title: "Migration",
      video: false,
      vote_average: 7.7,
      vote_count: 295,
    },
    {
      adult: false,
      backdrop_path: "/tLxjbT5ROZRwYcpNT3nfQbqkApk.jpg",
      genre_ids: [878, 12, 28],
      id: 609681,
      original_language: "en",
      original_title: "The Marvels",
      overview:
        "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
      popularity: 1902.848,
      poster_path: "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
      release_date: "2023-11-08",
      title: "The Marvels",
      video: false,
      vote_average: 6.371,
      vote_count: 1265,
    },
    {
      adult: false,
      backdrop_path: "/ehumsuIBbgAe1hg343oszCLrAfI.jpg",
      genre_ids: [16, 10751, 14, 12],
      id: 1022796,
      original_language: "en",
      original_title: "Wish",
      overview:
        "Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
      popularity: 1647.057,
      poster_path: "/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
      release_date: "2023-11-13",
      title: "Wish",
      video: false,
      vote_average: 6.481,
      vote_count: 454,
    },
    {
      adult: false,
      backdrop_path: "/ba9TgAO4I8RyA2LljzR3MspHaM9.jpg",
      genre_ids: [28, 878, 53],
      id: 799155,
      original_language: "hi",
      original_title: "Attack",
      overview:
        "With the Parliament under siege, India’s first super soldier Arjun Shergill is tasked to get hold of the terrorists in the nick of time, save the Prime Minister from their clutches and stop a dirty bomb from exploding and destroying Delhi. Will Arjun succeed in his mission?",
      popularity: 973.593,
      poster_path: "/5jGKbYuZtdxSNOocI6ZziQeiY4n.jpg",
      release_date: "2022-04-01",
      title: "Attack",
      video: false,
      vote_average: 7.2,
      vote_count: 53,
    },
    {
      adult: false,
      backdrop_path: "/vdpE5pjJVql5aD6pnzRqlFmgxXf.jpg",
      genre_ids: [18, 36],
      id: 906126,
      original_language: "es",
      original_title: "La sociedad de la nieve",
      overview:
        "On October 13, 1972, Uruguayan Air Force Flight 571, chartered to take a rugby team to Chile, crashes into a glacier in the heart of the Andes.",
      popularity: 965.245,
      poster_path: "/2e853FDVSIso600RqAMunPxiZjq.jpg",
      release_date: "2023-12-13",
      title: "Society of the Snow",
      video: false,
      vote_average: 8.089,
      vote_count: 1451,
    },
    {
      adult: false,
      backdrop_path: "/f1AQhx6ZfGhPZFTVKgxG91PhEYc.jpg",
      genre_ids: [36, 10752, 18],
      id: 753342,
      original_language: "en",
      original_title: "Napoleon",
      overview:
        "An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
      popularity: 947.665,
      poster_path: "/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg",
      release_date: "2023-11-22",
      title: "Napoleon",
      video: false,
      vote_average: 6.502,
      vote_count: 1461,
    },
    {
      adult: false,
      backdrop_path: "/rz8GGX5Id2hCW1KzAIY4xwbQw1w.jpg",
      genre_ids: [28, 35, 80],
      id: 955916,
      original_language: "en",
      original_title: "Lift",
      overview:
        "An international heist crew, led by Cyrus Whitaker, race to lift $500 million in gold from a passenger plane at 40,000 feet.",
      popularity: 1034.924,
      poster_path: "/gma8o1jWa6m0K1iJ9TzHIiFyTtI.jpg",
      release_date: "2024-01-10",
      title: "Lift",
      video: false,
      vote_average: 6.448,
      vote_count: 559,
    },
    {
      adult: false,
      backdrop_path: "/adNMDatnEnIEo4LUo1KyhouP6VA.jpg",
      genre_ids: [28, 18],
      id: 1212073,
      original_language: "de",
      original_title: "60 Minuten",
      overview:
        "Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.",
      popularity: 727.488,
      poster_path: "/jojfbnIHGsRpodIood3OQoqA45Y.jpg",
      release_date: "2024-01-19",
      title: "Sixty Minutes",
      video: false,
      vote_average: 6.777,
      vote_count: 128,
    },
    {
      adult: false,
      backdrop_path: "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
      genre_ids: [878, 10749, 35],
      id: 792307,
      original_language: "en",
      original_title: "Poor Things",
      overview:
        "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across the continents. Free from the prejudices of her times, she grows steadfast in her purpose to stand for equality and liberation.",
      popularity: 624.926,
      poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
      release_date: "2023-12-07",
      title: "Poor Things",
      video: false,
      vote_average: 8.178,
      vote_count: 489,
    },
    {
      adult: false,
      backdrop_path: "/yl2GfeCaPoxChcGyM5p7vYp1CKS.jpg",
      genre_ids: [28, 35, 10749],
      id: 848187,
      original_language: "en",
      original_title: "Role Play",
      overview:
        "Emma has a wonderful husband and two kids in the suburbs of New Jersey – she also has a secret life as an assassin for hire – a secret that her husband David discovers when the couple decide to spice up their marriage with a little role play.",
      popularity: 592.402,
      poster_path: "/7MhXiTmTl16LwXNPbWCmqxj7UxH.jpg",
      release_date: "2023-12-14",
      title: "Role Play",
      video: false,
      vote_average: 5.889,
      vote_count: 216,
    },
    {
      adult: false,
      backdrop_path: "/a0GM57AnJtNi7lMOCamniiyV10W.jpg",
      genre_ids: [16, 12, 14],
      id: 508883,
      original_language: "ja",
      original_title: "君たちはどう生きるか",
      overview:
        "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
      popularity: 581.842,
      poster_path: "/jDQPkgzerGophKRRn7MKm071vCU.jpg",
      release_date: "2023-07-14",
      title: "The Boy and the Heron",
      video: false,
      vote_average: 7.43,
      vote_count: 840,
    },
    {
      adult: false,
      backdrop_path: "/6OnoMgGFuZ921eV8v8yEyXoag19.jpg",
      genre_ids: [28, 53],
      id: 1211957,
      original_language: "en",
      original_title: "The Painter",
      overview:
        "An ex-CIA operative is thrown back into a dangerous world when a mysterious woman from his past resurfaces. Now exposed and targeted by a relentless killer and a rogue black ops program, he must rely on skills he thought he left behind in a high-stakes game of survival.",
      popularity: 574.987,
      poster_path: "/UZ0ydgbXtnrq8xZCI5lHVXVcH9.jpg",
      release_date: "2024-01-05",
      title: "The Painter",
      video: false,
      vote_average: 6.362,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
      popularity: 561.758,
      poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
      release_date: "2023-07-19",
      title: "Oppenheimer",
      video: false,
      vote_average: 8.1,
      vote_count: 6403,
    },
    {
      adult: false,
      backdrop_path: "/ruKNVJFViAyR4jguVboFXTskMOe.jpg",
      genre_ids: [53, 28, 27],
      id: 1028703,
      original_language: "en",
      original_title: "The OctoGames",
      overview:
        '8 contestants compete in 8 deadly, classic children\'s games. They seek fame beyond their wildest dreams, competing for the chance to take over the YouTube channel of the famous yet elusive masked YouTuber known only as "JaxPro".',
      popularity: 550.573,
      poster_path: "/qGz5rffXhegQH5PGUDiObqoOt06.jpg",
      release_date: "2022-10-07",
      title: "The OctoGames",
      video: false,
      vote_average: 5.186,
      vote_count: 43,
    },
    {
      adult: false,
      backdrop_path: "/xCt3Ha6hhHep5pwiW2FSenC59Gn.jpg",
      genre_ids: [28, 10752],
      id: 965571,
      original_language: "ru",
      original_title: "Время патриотов",
      overview:
        "The brothers Sultan and Bekzat Ibrayev are serving faithfully in the Armed Forces of Kazakhstan, and at the same time they are in family disagreement. Sultan is a valiant intelligence officer and Bekzat is a talented fighter pilot. While an international terrorist organization prepares a carefully planned attack on the country's strategically important facilities, the brothers have to face not only a mortal threat, but also face a family confrontation related to their dead father. Circumstances force them to unite in order to save human lives, and the brothers eventually understand that their homeland and family are the most valuable thing they have.",
      popularity: 520.923,
      poster_path: "/A4QM6oF4UNNhQh1f9pRdXvyKW5s.jpg",
      release_date: "2022-04-28",
      title: "Patriots Time",
      video: false,
      vote_average: 9.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: "/9uNCYl2qmg16FLarg3n3Ea0PBIG.jpg",
      genre_ids: [27, 53],
      id: 1216784,
      original_language: "en",
      original_title: "Sunrise",
      overview:
        "When an ex-cop named Fallon returns to the scene of a horrific crime, the residents of a rural town soon discover that this dark visitor is really a vampire who feeds on blood and fear. After he is befriended by a kind immigrant family, the instinctive killer is faced with a choice between revenge and redemption.",
      popularity: 490.598,
      poster_path: "/4aRvg2ybz646gciX5M6qaclunC2.jpg",
      release_date: "2024-01-19",
      title: "Sunrise",
      video: false,
      vote_average: 5.3,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/dvNrgldueQciabkYmlCnyhmaPoO.jpg",
      genre_ids: [28, 9648, 53, 27],
      id: 899445,
      original_language: "en",
      original_title: "Deep Fear",
      overview:
        "A solo trip aboard a yacht takes a terrifying turn when a woman encounters three drug traffickers clinging to the shattered remains of a boat. They soon force her to dive into shark-infested waters to retrieve kilos of cocaine from the sunken wreck.",
      popularity: 485.943,
      poster_path: "/wjYxOR1S4yonkLP9NTFpFTCTL7d.jpg",
      release_date: "2023-10-18",
      title: "Deep Fear",
      video: false,
      vote_average: 5.547,
      vote_count: 85,
    },
    {
      adult: false,
      backdrop_path: "/kWyQh9fCrgcMfhqZmqtp89Q0TrT.jpg",
      genre_ids: [35, 10749],
      id: 1072790,
      original_language: "en",
      original_title: "Anyone But You",
      overview:
        "After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
      popularity: 465.559,
      poster_path: "/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
      release_date: "2023-12-21",
      title: "Anyone But You",
      video: false,
      vote_average: 7.22,
      vote_count: 132,
    },
  ],
  total_pages: 42512,
  total_results: 850223,
};
